export const ALERT_SHOW = 'ALERT_SHOW'
export const ALERT_HIDE = 'ALERT_HIDE'

export const AUTHENTICATE_FROM_TOKEN = 'AUTHENTICATE_FROM_TOKEN'

export const IS_FETCHING_REQUEST = 'IS_FETCHING_REQUEST'
export const IS_FETCHING_SUCCESS = 'IS_FETCHING_SUCCESS'
export const IS_FETCHING_FAILURE = 'IS_FETCHING_FAILURE'
